# Load required libraries (please install them with install.packages()  if missing )
library(shiny)
library(shinydashboard)
library(shinyjs)
library(data.table)

# Include helper files
source('InitEnvironment.R')
source('functions.R')
#source('simpleService.R')

# Add URL prefix for loading additional resource, such as images
addResourcePath('resources',"www")

# Custom ShinyJS hack code to let the boxes collapse automatically
jscode <- "shinyjs.collapse = function(boxid) { $('#' + boxid).closest('.box').find('[data-widget=collapse]').click(); }";


ui <- dashboardPage(skin = "blue",
                   
  dashboardHeader(title = "Innovatos 2018"),
  dashboardSidebar(
    
    sidebarMenu(id = "tab",
                conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                                 tags$div("Loading...",id="loadmessage")
                ),
                tags$div(tags$p(" ")),
                tags$div(align="center",
                         img(src="resources/atos_codex_logo.png", align="center")
                ),tags$div(tags$p(" ")),
                menuItem("Welcome", tabName = "welcome", icon = icon("home")),
                sidebarMenuOutput("menu")
              
    )
    
  ),
  dashboardBody(
    useShinyjs(),
    extendShinyjs(text = jscode),
    tags$head(tags$meta(`http-equiv`="X-UA-Compatible",content="IE=edge"),     #   <meta http-equiv="X-UA-Compatible" content="IE=edge">
              tags$style(type="text/css", "
             #loadmessage {
                       position: fixed;
                       bottom: 0px;
                       left: 0px;
                       width: 100%;
                       padding: 5px 0px 5px 0px;
                       text-align: center;
                       font-weight: bold;
                       font-size: 100%;
                       color: #000000;
                       background-color: #85c1e9;
                       z-index: 105;
                       }
                       ")),
    tabItems(
      
      # Start of welcome tab
      tabItem(tabName = "welcome",
              fluidRow(
                
                box(title = "Welcome to Innovatos 2018", status="primary", solidHeader = TRUE,width = 12,
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/Innovatos2018.jpg", align="center")
                             ),tags$div(tags$p(" ")),
                             
                             tags$p("Innovatos is Atos yearly showcase of the latest technology and innovations. This year's theme is 'the future of work'. In various demo's, we will show artificial Intelligence, smart things, robotics, augmented reality and a diversity of other technologies we already use in our daily life and which are rapidly taking over all the old ways of working.")
                    )
                )
              ),
              fluidRow(
                box(title = "About this demo", status="primary", solidHeader = TRUE,width = 12,
                    tags$div(tags$p(" ")),
                    tags$div(align="center",
                             img(src="resources/basestation.jpg", align="center")
                    ),tags$div(tags$p(" ")),
                    
                    tags$p("This demo is shows the analytics behind mobile network optimizations in a step by step approach. The demo uses a fake dataset and is written in the R programming language. The interface is designed with Shiny."),
                    tags$p("This demo is inspired by a real client project, but all data generated by a randomized process. Any reference to existing persons or organizations is  therefore purely coincidental."),tags$div(tags$p(" "))
                )
              )
              ),

      ## End of Welcome tab
      # Start of welcome tab
      tabItem(tabName = "DataLoad",
              fluidRow(
                box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                    tags$p("In the boxes below you can select from which data source you want to load the data for the demo. To demonstrate the 
                            portability of data products, we included several connectors.")
                )),
              fluidRow(
                
                box(title = "Local Data", status="primary", solidHeader = TRUE,width = 6, height = "250px",
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/icon_disk.png", align="center"),
                                      tags$div(tags$p(" ")),
                                      actionButton('btnLoadLocal', label="Load Data from local disk", icon = icon("ok", lib = "glyphicon"), align="center")
                             ),tags$div(tags$p(" "))
                    )
                ),
                box(title = "HTTPS", status="primary", solidHeader = TRUE,width = 6, height = "250px",
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/icon_https.png", align="center"),
                                      textInput("dataHttpsURL", label = "", value = "https://pub.marcel.im/CodexDemo/cell_measurements.csv"),
                                      tags$div(tags$p(" ")),
                                      actionButton('btnLoadHTTPS', label="Load Data from HTTPS server", icon = icon("ok", lib = "glyphicon"), align="center")
                             ),tags$div(tags$p(" "))
                    )
                )
      
              ),
              fluidRow(
                box(title = "Azure Cloud", status="primary", solidHeader = TRUE,width = 6,height = "250px",
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/icon_azure.png", align="center"),
                                      tags$div(tags$p(" ")),
                                      tags$p("Under construction")
                             ),tags$div(tags$p(" "))
                    )
                ),
                box(title = "Atos Codex", status="primary", solidHeader = TRUE,width = 6, height = "250px",
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/icon_codex.png", align="center"),
                                      tags$div(tags$p(" ")),
                                      tags$p("Under construction")
                             ),tags$div(tags$p(" "))
                    )
                )
              ),
              fluidRow(
                box(title = "Siemens Mindsphere", status="primary", solidHeader = TRUE,width = 6, height = "250px",
                    tags$div(class="header", checked=NA,
                             tags$div(tags$p(" ")),
                             tags$div(align="center",
                                      img(src="resources/icon_mindsphere.png", align="center"),
                                      tags$div(tags$p(" ")),
                                      tags$p("Under construction")
                             ),tags$div(tags$p(" "))
                    )
                )
              )
  ),# End of Data Load tab
  # Begin of the Data tab.
  
  tabItem(tabName = "Dataset",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("In the table below you see the source data that is used in this analysis case. This demo uses two sources of data. The first
                       dataset contains the measurements. The second dataset contains the cell location data (master data).")
            )),
          fluidRow(
            box(title = "Dataset Viewer", status = "primary", solidHeader = TRUE,width = 12,
            tabBox(
              title = "Source Data", width = 12, #status = "primary", solidHeader = TRUE, width = 12,
              # The id lets us use input$tabset1 on the server to find the current tab
              id = "tabsetDatSet",# height = "250px",
              tabPanel("Cell Measurements", tags$div(DT::dataTableOutput('dtViewDataset'), style = "font-size:80%")),
              tabPanel("Cell Locations", tags$div(DT::dataTableOutput('dtViewDatasetLoc'), style = "font-size:80%"))
            ))
        
                
            )
          ),
  # End of the dataset tab
  
  # Begin of data clean tab
  tabItem(tabName = "DataClean",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("In the overview below, we illustrate one of the difficulties we encounter: Matching data! In order to 
                       join measurement data to location data, we need to calculate a key-field called the E-UTRAN Cell Identifier (ECI).")
            )),
          fluidRow(
            box(title = "Calculating the ECI from the eNodeB-IDentifier and Cell ID?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("Here is the formula: ECI = 2^8 * eNBId + Cellid")
            )),
          fluidRow(
            box(title = "Set 1: Measurements", status = "primary", solidHeader = TRUE,width = 6, height = "550px",
                tags$div(DT::dataTableOutput('dtViewMeasureKey'), style = "font-size:80%")),
            box(title = "Set 2: Location data (master data)", status = "primary", solidHeader = TRUE,width = 6, height = "550px",
                tags$div(DT::dataTableOutput('dtViewLocationKey'), style = "font-size:80%"))
          ),
          fluidRow(
            box(title = "Combined Dataset", status = "primary", solidHeader = TRUE,width = 12,
                tags$div(DT::dataTableOutput('dtCombined'), style = "font-size:80%"))
            )
  ), # End of data clean tab
  
  # Begin of the density compare tab
  
  tabItem(tabName = "DataExplore",
          fluidRow(
            box(title = "Selection variable", status = "primary", solidHeader = TRUE,width = 6,
                selectInput("selectVarNameForHist",label = "Variable:",choices = NULL)
            ),
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 6,
                tags$p("Below we explore the spread of the selected measurement. The first graph is a standard histogram of all the values. In the second graph, a
                       boxplot is shown. This illustrates the number of outliers we have in our dataset. In the fourth plot, we plot the timeseries data
                       for all cells, for the selected measurement. The fifth plot performs an anomaly detection on the timeseries data of one cell. Finally, the
                       summary statistics are shown on the bottom.")
                )
          ),
          fluidRow(
            box(title = "Histogram", status = "primary", solidHeader = TRUE,width = 6,
                plotOutput("HistPlot",height="250px") 
            ),
            box(title = "Boxplot", status = "primary", solidHeader = TRUE,width = 6,
                plotOutput("BoxPlot",height="250px") 
            )
          ),
          fluidRow(
            box(title = "Timeseries", status = "primary", solidHeader = TRUE,width = 6, height="400px",
                plotOutput("TSPlot",height="250px", width="550px") 
            ),
            box(title = "Anomaly Detection", status = "primary", solidHeader = TRUE,width = 6, height="400px",
                selectInput("selectCellForAnom",label = "Cell ID:",choices = NULL),
                plotOutput("AnomalyPlot",height="250px", width="550px") 
            )
            
            ),
          fluidRow(
            box(title = "Summary statistic", status = "primary", solidHeader = TRUE,width = 12,
                verbatimTextOutput("Out_summary")
            )
          )
          
          ),
  
  # End of the density compare tab
  
  # Begin of cell locations tab
  tabItem(tabName = "CellLocations",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("After joining the datasets, you can see the location of each cell on the map of Amsterdam.")
            )),
          fluidRow(
            box(title = "Cell Location", status = "primary", solidHeader = TRUE,width = 12,
                tags$div(align="center",plotOutput("CellLocationsPlot", width = "800px", height = "800px"))
            )
          )),
  # End of Cell Locations tab
  
  # Begin of Capacity Analysis
  tabItem(tabName = "CapacityAnalysis",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("In this section, we describe some of the steps we do to determine whether a cell is having a capacity issue.
                       For this, we look at some the measurement channels are try to identify relevant cut-off points.")
            )),
          fluidRow(
            box(title = "Detecting Capacity Issues", status = "primary", solidHeader = TRUE,width = 12,
                tabBox(
                  title = "Capacity Analysis", width = 12, #status = "primary", solidHeader = TRUE, width = 12,
                  # The id lets us use input$tabset1 on the server to find the current tab
                  id = "tabsetDatSet",# height = "250px",
                  tabPanel("Scatterplot", 
                           sliderInput("maxSamples", "Random samples to plot:",
                                       min = 1, max = 100000,
                                       value = 10000, step = 1000),
                           actionButton('btnRenderScatter', label="Render plot", icon = icon("ok", lib = "glyphicon")),
                           
                           plotOutput("CapacityScatterPlot", height="750px") ),
                  tabPanel("Cells with Capacity Problems", tags$div(
                    sliderInput("cutoffLic", "Cut-off for Licenses:",
                                min = 0, max = 1,
                                value = 0.8, step = 0.05),
                    sliderInput("cutoffHW", "Cut-off for Hardware:",
                                min = 0, max = 100,
                                value = 80, step = 5),
                    DT::dataTableOutput('dtCellsWithProblems'), style = "font-size:80%")),
                  tabPanel("Location", plotOutput("CellIssueLocPlot")) 
                  )
                
                   
            )
          )),
  # End of Cell Locations tab

  # Begin of load balance
  tabItem(tabName = "LoadBalance",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("After performing the capacity analysis on a cell level, we look at opportunities for load balancing. For our
                       Mobile Network equipment company, we want to use this insight to target upsell opportunities")
            )),
          fluidRow(
            box(title = "Suggested Cells for 4G/LTE Load Balancing Upgrade", status = "primary", solidHeader = TRUE,width = 6,
                plotOutput("LoadBalanceLocPlot")),
            box(title = "Shoppinglist", status = "primary", solidHeader = TRUE,width = 6,
                DT::dataTableOutput('dtShoppingList'))
  )
  ),
  # End of load balance tab
  # Begin of tab API service
  tabItem(tabName = "API",
          fluidRow(
            box(title = "What is this?", status = "primary", solidHeader = TRUE,width = 12,
                tags$p("Finally, in order to demonstrate the value of REST APIs and micro-services, we are able to expose
                       some of the analytics as a service. Below buttons allow us to start/stop the REST API. Please remember to 
                       stop the service, before restarting the app.")
            )),
          fluidRow(
            box(title = "Exposing thise as a Service (REST API)? ", status = "primary", solidHeader = TRUE,width = 6, height="500px",
                tags$p("The functionality can be exposed as a service. After pressing Start, a small Jug server will run
                       in the background, accepting requests."),
                tags$div(tags$p(" ")),tags$div(tags$p(" ")),
                actionButton('btnStartService', label="Start service", icon = icon("ok", lib = "glyphicon")),
                actionButton('btnStopService', label="Stop service", icon = icon("stop", lib = "glyphicon"))
                ),
            box(title = "How to connect?", status = "primary", solidHeader = TRUE,width = 6, height="500px",
                tags$p("This services exposes 2 endpoints. You can use the following Curl command to test them."),
                tags$p("* Capacity Issue Service:"),tags$p("curl -s http://192.168.2.30:8080/detectCapacityIssues "),
                tags$p("* Shopppinglist Service:"),tags$p("curl -s http://192.168.2.30:8080/getShoppingList ")
                
          ))
  )  # End of tab API service
  
    ) # End of tab items
) # End of Dashboard Body

) # End of UI
